version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT.dkr.ecr.$AWS_REGION.amazonaws.com
  build:
    commands:
      - echo Building the Docker image on `date`
      - docker build --no-cache -f build/app/Dockerfile.prod -t ent-example .
      - docker tag ent-example:latest $AWS_ACCOUNT.dkr.ecr.$AWS_REGION.amazonaws.com/ent-example:latest
  post_build:
    commands:
      - echo Pushing the Docker image on `date`
      - docker push $AWS_ACCOUNT.dkr.ecr.$AWS_REGION.amazonaws.com/ent-example:latest
