name: Build and Push Docker Images to ECR Repositories

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ap-northeast-1
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT }}:role/role-github
          role-duration-seconds: 1800

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          docker build -t $ECR_REGISTRY/eks-app:$IMAGE_TAG -f ./build/app/Dockerfile.prod .
          docker build -t $ECR_REGISTRY/eks-web:$IMAGE_TAG -f ./build/web/Dockerfile .
          docker build -t $ECR_REGISTRY/eks-migration:$IMAGE_TAG -f ./build/migration/Dockerfile .
          docker push $ECR_REGISTRY/eks-web:$IMAGE_TAG
          docker push $ECR_REGISTRY/eks-app:$IMAGE_TAG
          docker push $ECR_REGISTRY/eks-migration:$IMAGE_TAG
      
      - name: Checkout config repository
        uses: actions/checkout@v3
        with:
          repository: k-akari/myk8s
          path: myk8s
          ref: main
          token: ${{ secrets.PAT }}

      - name: Update image tag
        id: update-image-tag
        working-directory: myk8s
        continue-on-error: true
        run: |
          yq -i '.front.imageTag = "'`printenv IMAGE_TAG`'"' ./main/values.yaml
          git diff --name-only --exit-code

      - name: Commit and push
        working-directory: myk8s
        if: steps.update-image-tag.outcome == 'failure'
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add .
          git commit --author=. -m "Update image tag to "`printenv IMAGE_TAG`
          git push
