name: Build and Push Docker Images to ECR Repositories

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ap-northeast-1
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT }}:role/role-github
          role-duration-seconds: 1800

      - run: aws sts get-caller-identity

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          docker build -t $ECR_REGISTRY/eks-app:$IMAGE_TAG -f ./build/app/Dockerfile.prod .
          docker build -t $ECR_REGISTRY/eks-web:$IMAGE_TAG -f ./build/web/Dockerfile .
          docker build -t $ECR_REGISTRY/eks-migration:$IMAGE_TAG -f ./build/migration/Dockerfile .
          docker push $ECR_REGISTRY/eks-web:$IMAGE_TAG
          docker push $ECR_REGISTRY/eks-app:$IMAGE_TAG
          docker push $ECR_REGISTRY/eks-migration:$IMAGE_TAG

      - name: Update manifest
        run: |
          git config --global user.email ${{ secrets.EMAIL }}
          git config --global user.name k-akari
          git clone https://github.com/k-akari/myk8s.git
          yq write -i main/values.yaml front.imageTag $IMAGE_TAG
          git add .
          git commit -m ${{ github.run_number }} -a
          git push origin maine
